version: '3'
services:
  mariadb_temp:
    image: mariadb:latest
    restart: always
    ports:
      - 33061:3306
    volumes:
      - /mnt/c/Users/hem/data:/data/
      - /mnt/c/Users/hem/mysql_data/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=dbtest
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 18088:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb_temp
  jupyter_all:
    image: jupyter/all-spark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - /mnt/c/Users/hem/data:/home/jovyan/data/
      - /mnt/c/Users/hem/git/PyMLLab/:/home/jovyan/PyMLLab/
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    user: root
    depends_on:
      - mariadb_temp
volumes:
  v_jupyter_all: