version: '3'
services:
  mariadb_temp:
    image: mariadb:latest
    restart: always
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=dbtest
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 18088:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb_temp