version: "3"
services:
  web:
    image: beercafeguy/python_app:ver1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports: 
      - "4000:80"
      - "4001:81"
    networks:
      - webnet
networks:
  webnet:
